init
Aroo-dev/Student-Man-System pull request #1
Opened 2023-02-25 11:56 UTC by Aroo-dev

2023-02-25 11:58 UTC, raxigan commented on src/main/resources/application.properties
> +spring.profiles.active=
why not yaml

2023-03-07 19:02 UTC, raxigan requested changes

2023-03-07 19:02 UTC, raxigan commented on docker-compose.yaml
> +
Leave just one empty line

2023-03-07 19:02 UTC, raxigan commented on docker-compose.yaml
> +
Leave just one empty line

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +            <artifactId>cache-api</artifactId>
Is it used for anything?

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +            <scope>runtime</scope>
Why runtime?

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +            <version>3.0.3</version>
I suggest to inherit some of the dependencies versions from spring boot parent pom. I see you can inherit at least:
- spring-boot-starter-cache
- ehcache
- postgresql
- spring-boot-starter-validation
- spring-context-support
- spring-boot-starter-mail
- spring-boot-starter-actuator
- spring-boot-starter-security

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation -->
Remove those comments.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/JavaAdminApplication.java
> +        System.out.println("dwawaddwadwawaddwadwawaddwa");
Remove those sysouts

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/email/EmailSenderService.java
> +@RequiredArgsConstructor
Add empty line

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/email/EmailSenderService.java
> +
Leave just one empty line

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/exception/BadAuthenticationException.java
> +
Leave just one empty line

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/exception/EmailAlreadyTakenException.java
> +
Leave just one empty line

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/exception/EmailNotFoundException.java
> +
Leave just one empty line. The only place where 2 empty lines are allowed is between imports and class name.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/role/Role.java
> +
Remove empty lines

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/InstructorService.java
> +     void removeInstructor(Long id);
Format the code

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/student/StudentServiceImpl.java
> +@Transactional
Shouldn't it be `@Transactional` from spring?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/InstructorServiceImpl.java
> +@Transactional
```suggestion
@Transactional(readOnly = true)
```

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/InstructorServiceImpl.java
> +@Transactional
After changing it to read only override the write methods with just `@Transactional`

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/course/CourseRepository.java
> +    @Query(value = "select * from courses as c where c.course_id in (select  e.course_fk from enrolled as e where e.student_fk =:studentId)", nativeQuery = true)
Try to not use native query unless it's the only option.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/course/CourseRepository.java
> +//    @Query(value = "SELECT i from Course  as i where i.students.=:email")
Remove this

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/exception/EmailAlreadyTakenException.java
> +public class EmailAlreadyTakenException extends RuntimeException {
Maybe it would be better to just use `ResponseStatusException`. It could replace most of your custom exception classes. Maybe you could also get rid of `ErrorDetails` thanks to that.

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +                            <groupId>org.projectlombok</groupId>
Why you exclude lombok here?

2023-03-07 19:02 UTC, raxigan commented on pom.xml
> +            <scope>runtime</scope>
Why runtime?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/course/Course.java
> +import javax.persistence.*;
Don't use wildcard imports.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/course/CourseDTO.java
> +    public CourseDTO(String name, Duration duration, String description, InstructorDTO instructor) {
Why so many unused contructors?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/email/EmailSenderService.java
> +    private static final String HOST_EMAIL = "axxrxxo@gmail.com";
Don't put any mail addresses, passwords and any confidential data to your repositories (especially the public ones!). Provide them via environment variables.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/InstructorDTO.java
> +    public String toString() {
Isn't lombok `toString` enough?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/user/UserServiceImpl.java
> +                throw new NullPointerException(ROLE_NOT_FOUND);
Change this NPE to some more descriptive exception.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/user/UserServiceImpl.java
> +
Remove those empty lines

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/security/AuthenticationHandler.java
> +    public Instructor authenticateInstructor(InstructorDTO instructorDTO, Authentication authentication) {
Both methods in this class are almost the same. I think you can write a new one that can handle both cases in same time.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
At least most of the cases could be handled by `ResponseStatusException`.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/Instructor.java
> +public class Instructor {
Can there be a case in real life when an instructor is student in same time? I think so... How such case will be handled?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/instructor/InstructorServiceImpl.java
> +    public void removeInstructor(Long id) {
Cannot you use cascade deletion here?

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/security/JWTHelper.java
> +    private static final long EXPIRE_ACCESS_TOKEN = TimeUnit.MINUTES.toNanos(10);
Try to avoid such small units like nanos or micros. I'd probably use seconds here. Also this constant name should rather be a noun.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/security/JWTHelper.java
> +                .withExpiresAt(Instant.now().plusSeconds(EXPIRE_REFRESH_TOKEN))
In `EXPIRE_REFRESH_TOKEN` you have nanos, but use seconds here.

2023-03-07 19:02 UTC, raxigan commented on src/main/java/com/aro/javaadmin/security/JWTHelper.java
> +        Map<String, String> idToken = new HashMap<>();
```suggestion
       return Map.of("accessToken", jwtAccessToken, "refreshToken", jwtRefreshToken);
```

2023-03-08 07:54 UTC, raxigan requested changes

2023-03-08 07:54 UTC, raxigan commented on src/main/java/com/aro/javaadmin/student/StudentDTO.java
> +    private User user;
Entity should not be a part of DTO. If you want to keep this design use existing UserDTO. Second thing is that any passwords once put into a system should never leave it at any circumstances. They are only collected to be processed internally and should never be exposed - no matter if it's a secured API or not.

2023-03-08 08:55 UTC, Aroo-dev commented on pom.xml
> +            <artifactId>cache-api</artifactId>
at the first glance i thought i might need this dependency but found a different third library that can handle it. deleted

2023-03-08 08:56 UTC, Aroo-dev commented on pom.xml
> +            <scope>runtime</scope>
deleted scope

2023-03-08 08:56 UTC, Aroo-dev commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation -->
removed

2023-03-08 08:58 UTC, Aroo-dev commented on pom.xml
> +                            <groupId>org.projectlombok</groupId>
deleted those bad configs

2023-03-08 08:58 UTC, Aroo-dev commented on src/main/java/com/aro/javaadmin/JavaAdminApplication.java
> +        System.out.println("dwawaddwadwawaddwadwawaddwa");
removed

2023-03-08 09:04 UTC, Aroo-dev commented on src/main/java/com/aro/javaadmin/course/Course.java
> +import javax.persistence.*;
fixed

2023-06-08 20:15 UTC, merged